# ===============================
# SERVER CONFIG
# ===============================
server.port=${PORT:8080}

# ===============================
# DATABASE (POSTGRESQL - RENDER)
# ===============================
spring.datasource.url=jdbc:postgresql://dpg-d72f34m3jp1c73edvvng-a.oregon-postgres.render.com:5432/medicinedb_f61o
spring.datasource.username=pavani
spring.datasource.password=SjPeWG6z4GY3QopkKfflPz3Ls1SwDO44
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JACKSON
# ===============================
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.fail-on-empty-beans=false

# ===============================
# LOGGING
# ===============================
logging.level.com.medicinereminder=DEBUG
logging.level.org.springframework=DEBUG

# ===============================
# ERROR DEBUGGING
# ===============================
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always